---
- name: Add hosts in groups by Jenkins
  hosts: localhost
  remote_user: ubuntu

  roles:
    - crgroup

- name: building the project on build vm
  hosts: building
  remote_user: jenkins
  become: yes

  roles:
    - build

- name: run the project on prod vm
  hosts: production
  remote_user: ubuntu
  become: yes

  roles:
    - prod