---
# tasks file for prod
- name: install default-jdk & tomcat9 on production server
  apt: name={{item}} state=present update-cache=yes
  with_items:
    - python3-pip
    - docker.io

- name: install pip install docker-py
  pip:
    name: docker-py

- name: log into DockerHub
  docker_login:
    username: "{{ lookup('ini', 'Username type=properties file=../../dockercreds.properties') }}"
    password: "{{ lookup('ini', 'Password type=properties file=../../dockercreds.properties') }}"
#    username: grandhustla
#    password: Ublpbycrbq220419911!

- name: pull an image
  docker_image:
    name: grandhustla/certwork:2.0.1
    pull: yes

- name: run the image
  docker_container:
    name: certwork
    image: grandhustla/certwork:2.0.1
    state: started
    ports:
      - "8080:8080"